src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Length(
    min: 3,
    max: 255,
    minMessage: 'Votre titre doit faire au moins {{ limit }} caractères de long',
    maxMessage: 'Votre titre doit faire au maxmium {{ limit }} caractères de long',
    )]
    private $title;

    #[ORM\Column(type: 'text', nullable: true)]
    #[Assert\Length(
    max: 1200,
    maxMessage: 'Votre description doit faire au maxmium {{ limit }} caractères de long',
    )]
    private $commentaire;

    #[ORM\Column(type: 'integer')]
    private $rating;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $modified_at;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'avis')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToOne(targetEntity: Boutique::class, inversedBy: 'avis')]
    #[ORM\JoinColumn(nullable: false)]
    private $boutique;

    #[ORM\Column(type: 'boolean')]
    private $actif;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTimeImmutable $modified_at): self
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBoutique(): ?Boutique
    {
        return $this->boutique;
    }

    public function setBoutique(?Boutique $boutique): self
    {
        $this->boutique = $boutique;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }
}

src/Entity/Conversation.php
<?php

namespace App\Entity;

use App\Repository\ConversationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ConversationRepository::class)]
class Conversation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $premier_message;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $modified_at;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'conversations_init')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'conversations_corresp')]
    #[ORM\JoinColumn(nullable: false)]
    private $correspondant;

    #[ORM\OneToMany(mappedBy: 'conversation', targetEntity: Message::class)]
    private $messages;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $is_read;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPremierMessage(): ?string
    {
        return $this->premier_message;
    }

    public function setPremierMessage(string $premier_message): self
    {
        $this->premier_message = $premier_message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTimeImmutable $modified_at): self
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCorrespondant(): ?User
    {
        return $this->correspondant;
    }

    public function setCorrespondant(?User $correspondant): self
    {
        $this->correspondant = $correspondant;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setConversation($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getConversation() === $this) {
                $message->setConversation(null);
            }
        }

        return $this;
    }

    public function isIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(?bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }
}

src/Controller/Profil/MessagerieUserController.php
<?php 

namespace App\Controller\Profil;

use App\Controller\DefaultController;
use App\Entity\User;
use App\Entity\Message;
use App\Form\MessageType;
use App\Entity\Conversation;
use App\Form\ConversationType;
use App\Repository\MessageRepository;
use App\Repository\ConversationRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/profil')]
class MessagerieUserController extends AbstractController
{
    #[Route('/user/messagerie', name: 'user_messagerie')]
    public function messagerieUser(Request $request, PaginatorInterface $paginator, DefaultController $defaultController)
    {
        $user = $this->getUser();
        $conversationsCorresp = $user->getConversationsCorresp();
        $conversationsInit = $user->getConversationsInit();
        $conversations = [];

        
        $nbrNonlus = 0;
        $tabNbrNonlus = [];

        foreach ($conversationsCorresp as $key => $conv) {
            $conversations[] = $conv;
            if ($conv->isIsRead() === false) {
                $nbrNonlus = $nbrNonlus + 1;
            }
            foreach ($conv->getMessages() as $key => $mess) {
                if ($mess->isIsRead() === false && $mess->getExpediteur()->getId() != $this->getUser()->getId()) {
                    $nbrNonlus += 1;
                }
            }
            $tabNbrNonlus[$conv->getId()] = $nbrNonlus;
            $nbrNonlus = 0;
        }
        foreach ($conversationsInit as $key => $conv) {
            $conversations[] = $conv;
            foreach ($conv->getMessages() as $key => $mess) {
                if ($mess->isIsRead() == false && $mess->getExpediteur()->getId() != $this->getUser()->getId()) {
                    $nbrNonlus += 1;
                }
            }
            $tabNbrNonlus[$conv->getId()] = $nbrNonlus;
            $nbrNonlus = 0;
        }
        usort($conversations, function(Conversation $a, Conversation $b){
            return $a->getModifiedAt()>$b->getModifiedAt()?-1:1;
        });
        $conversations = $defaultController::maPagination($conversations, $paginator, $request, 5);

        return $this->renderForm('front/profil/messagerie/messagerie.html.twig', [
            'conversations' => $conversations,
            'tabNbrNonlus' => $tabNbrNonlus
        ]);
    }

    #[Route('/new-conversation-user/{id}', name: 'new_conversation_user')]
    public function newConversation(Request $request, ConversationRepository $conversationRepository, User $user): Response
    {
        $conversation = new Conversation();
        $form = $this->createForm(ConversationType::class, $conversation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $conversation->setCreatedAt(new \DateTimeImmutable());
            $conversation->setModifiedAt(new \DateTimeImmutable());
            $conversation->setIsRead(false);
            $conversation->setUser($this->getUser());
            $conversation->setCorrespondant($user);
            $conversationRepository->add($conversation, true);

            return $this->redirectToRoute('user_messagerie', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/profil/messagerie/new_conversation.html.twig', [
            'conversation' => $conversation,
            'form' => $form,
        ]);
    }

    #[Route('/user/messagerie/{id}', name: 'user_messagerie_message')]
    public function newMessage(Request $request, MessageRepository $messageRepository, Conversation $conversation, ConversationRepository $conversationRepository): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($conversation->getCorrespondant()->getId() === $this->getUser()->getId()) {
            if ($conversation->isIsRead() === false) {
                $conversation->setIsRead(true);
            }
            foreach ($conversation->getMessages() as $key => $mess) {
                if ($mess->getExpediteur()->getId() != $this->getUser()->getId()) {
                    $mess->setIsRead(true);
                }
            }
        }
        $conversationRepository->add($conversation, true);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setConversation($conversation);
            $message->setIsRead(false);
            $message->setExpediteur($this->getUser());
            $message->setCreatedAt(new \DateTimeImmutable());
            $messageRepository->add($message, true);

            $conversation->setModifiedAt(new \DateTimeImmutable());
            $conversationRepository->add($conversation, true);

            return $this->redirectToRoute('user_messagerie_message', ['id' => $conversation->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/profil/messagerie/message.html.twig', [
            'message' => $message,
            'form' => $form,
            'conversation' => $conversation
        ]);
    }
}

templates/front/profil/messagerie/message.html.twig
{% extends 'layout/front_profil_base.html.twig' %}

{% block title %}
    <title>Conversation</title>
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('Messagerie') }}
{% endblock %}

{% block container %}
    <h1 class="title_top">Conversation</h1>
    {% if conversation.user.email == app.user.email %}
        <div class="conv_with_box">
            <div class="conv_with">Conversation avec {{ conversation.correspondant.name }}</div>
            <div>
            {% set user = conversation.correspondant %}
            {% include '_partials/_photo_profile.html.twig' %}
            </div>
        </div>
    {% endif %}
    <div class="chat-container">
        <ul class="chat-box chatContainerScroll">
            {# Première bulle #}
            {% if conversation.user.email == app.user.email %}
                <p class="chat_date">{{ conversation.createdAt|date('d/m/y') }}</p>
                <li class="chat-left">
                    <div class="chat-avatar">
                        {% if app.user.image %}
                            <img src="{{ asset('uploads/profile/'~app.user.image) }}" alt="image de profil">
                        {% else %}
                            <img src="{{ asset('images/default-profile-picture.jpg') }}" alt="image de profil par défaut">
                        {% endif %}
                        <div class="chat-name">{{ conversation.user.name }}</div>
                    </div>
                    <div class="chat-text">{{ conversation.premierMessage }}</div>
                    <div class="chat-hour">{{ conversation.createdAt|date('H:i') }}<span class="fa fa-check-circle"></span></div>
                </li>
            {% else %}
                <p class="chat_date">{{ conversation.createdAt|date('d/m/y') }}</p>
                <li class="chat-left">
                    <div class="chat-avatar">
                        {% if conversation.user.image %}
                            <img src="{{ conversation.user.image }}" alt="Image de profil">
                        {% else %}
                            <img src="{{ asset('images/default-profile-picture.jpg') }}" alt="image de profil par défaut">
                        {% endif %}
                        <div class="chat-name">{{ conversation.user.name }}</div>
                    </div>
                    <div class="chat-text">{{ conversation.premierMessage }}</div>
                    <div class="chat-hour">{{ conversation.createdAt|date('H:i') }}<span class="fa fa-check-circle"></span></div>
                </li>
            {% endif %}
            {# Deuxième bulle et suite #}
            {% for message in conversation.messages %}
                {% if message.expediteur.email == conversation.user.email %}
                    <p class="chat_date">{{ message.createdAt|date('d/m/y') }}</p>
                    <li class="chat-left">
                        <div class="chat-avatar">
                            {% if conversation.user.image %}
                                    <img src="{{ asset('uploads/profile/'~conversation.user.image) }}" alt="image de profil">
                                {% else %}
                                    <img src="{{ asset('images/default-profile-picture.jpg') }}" alt="image de profil par défaut">
                                {% endif %}
                            <div class="chat-name">{{ conversation.user.name }}</div>
                        </div>
                        <div class="chat-text">{{ message.message }}</div>
                        <div class="chat-hour">{{ message.createdAt|date('H:i') }}<span class="fa fa-check-circle"></span></div>
                    </li>
                {% elseif message.expediteur.email == conversation.correspondant.email %}
                    <p class="chat_date chat-right">{{ message.createdAt|date('d/m/y') }}</p>
                    <li class="chat-right">
                        <div class="chat-hour">{{ message.createdAt|date('H:i') }}<span class="fa fa-check-circle"></span></div>
                        <div class="chat-text">{{ message.message }}</div>
                        <div class="chat-avatar">
                            {% if conversation.correspondant.image %}
                                <img src="{{ asset('uploads/profile/'~conversation.correspondant.image) }}" alt="image de profil">
                            {% else %}
                                <img src="{{ asset('images/default-profile-picture.jpg') }}" alt="image de profil par défaut">
                            {% endif %}
                            <div class="chat-name">{{ conversation.correspondant.name }}</div>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
        <div class="form-outline custom">
            {{ form_start(form, {attr : {novalidate: 'novalidate', class: 'width-100 d-flex row-wrap'}}) }}
                {{ form_widget(form.message) }}
                <div class="align_button">
                    <div class="block_buttons chat_submit">
                        {{ form_widget(form.submit) }}
                        <div class="form-error width-100">
                            {{ form_errors(form.message) }}
                        </div>
                    </div>
                </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="bloc_form btn-custom chat">
        <span class="hover-effect">
                <a href="{{ path('user_messagerie') }}">Retour</a>
        </span>
    </div>
{% endblock %}

templates/front/profil/messagerie/messagerie.html.twig
{% extends 'layout/front_profil_base.html.twig' %}

{% block title %}
    <title>Messagerie</title>
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('Messagerie') }}
{% endblock %}

{% block container %}
    <h1 class="title_top">Mes conversations</h1>
        <div class="messagerie_listing">
            <div class="users-container">
                <ul class="users">
                    {% for conv in conversations %}
                        <li class="person" data-chat="person1">
                            <div class="box_user">
                                <div class="user">
                                    {% if conv.user.id % 2 == 0 %}
                                            <span class="status online"></span>
                                        {% elseif conv.user.id % 3 == 0 %}
                                            <span class="status away"></span>
                                        {% elseif conv.user.id % 5 == 0 %}
                                            <span class="status busy"></span>
                                        {% else %}
                                            <span class="status offline"></span>
                                    {% endif %}
                                    {% set user = conv.user %}
                                    {% include '_partials/_photo_profile.html.twig' %}
                                </div>
                                <p class="name-time">
                                    {% if conv.user.name == app.user.name %}
                                        <span class="time init">Conversation commencée par vous</span><br>
                                        <span class="name">{{ app.user.name }}</span>
                                    {% else %}
                                        <span class="name">{{ conv.user.name }}</span>
                                    {% endif %}
                                    {% if conv.modifiedAt == null %}
                                        <span class="time">{{ conv.createdAt|date('d/m/Y') }}</span>
                                    {% else %}
                                        <span class="time">{{ conv.modifiedAt|date('d/m/Y') }}</span>
                                    {% endif %}
                                </p>
                            </div>
                            {# Si utilisateur est expéditeur #}
                            {% if conv.user.name == app.user.name %}
                            <div class="box_user">
                            {% for key, nbr in tabNbrNonlus %}
                                {% if conv.id == key %}
                                    {% if nbr > 0 %}
                                        <div class="block_buttons chat see new">
                                            <div class="box_name_time">
                                                <a title="Voir la conversation" class="conv" href="{{ path('user_messagerie_message', {id: conv.id}) }}">
                                                    Messages non lus {{ nbr }}
                                                </a>
                                            </div>
                                        </div>
                                    {% else %}
                                    <div class="block_buttons chat see none">
                                            <div class="box_name_time">
                                            <a title="Voir la conversation" class="conv" href="{{ path('user_messagerie_message', {id: conv.id}) }}">
                                                Pas de nouveaux messages
                                            </a>
                                        </div>
                                    </div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                                <div class="user">
                                    {% if conv.user.id % 2 == 0 %}
                                        <span class="status online"></span>
                                    {% elseif conv.user.id % 3 == 0 %}
                                        <span class="status away"></span>
                                    {% elseif conv.user.id % 5 == 0 %}
                                        <span class="status busy"></span>
                                    {% else %}
                                        <span class="status offline"></span>
                                    {% endif %}
                                    {% if conv.user.email == app.user.email %}
                                        {% set user = conv.correspondant %}
                                        {% include '_partials/_photo_profile.html.twig' %}
                                    {% endif %}
                                </div>

                                <p class="name-time">
                                    <span class="time dest">Destinataire</span><br><span class="name">{{ conv.correspondant.name }}</span>
                                </p>
                            </div>
                        {% else %}
                        {% for key, nbr in tabNbrNonlus %}
                                {% if conv.id == key %}
                                    {% if nbr > 0 %}
                                        <div class="block_buttons chat see new">
                                            <div class="box_name_time">
                                                <a title="Voir la conversation" class="conv" href="{{ path('user_messagerie_message', {id: conv.id}) }}">
                                                    Messages non lus {{ nbr }}
                                                </a>
                                            </div>
                                        </div>
                                    {% else %}
                                    <div class="block_buttons chat see none">
                                        <div class="box_name_time">
                                            <a title="Voir la conversation" class="conv" href="{{ path('user_messagerie_message', {id: conv.id}) }}">
                                                Pas de nouveaux messages
                                            </a>
                                        </div>
                                    </div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        </li>
                    {% else %}
                </ul>
                <h3 class="text-center mess m-5">Pas de conversation...</h3>
                <div class="security"></div>
                {% endfor %}
            </div>
        </div>
    <div class="js-filter-pagination" id="pagination_box">
        {{ knp_pagination_render(conversations) }}
    </div>
{% endblock %}

templates/front/profil/messagerie/new_conversation.html.twig
{% extends 'layout/front_profil_base.html.twig' %}

{% block title %}
    <title>Nouveau message</title>
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('Formulaires') }}
{% endblock %}

{% block container %}
<div id="main">
    <h2 class="title_top">Démarrer une conversation</h2>
    {% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}
    <div class="body">
        <div id="contener_form">
            {{ form_start(form, {attr : {novalidate: 'novalidate'}}) }}
                <div class="bloc_form">
                    {{ form_label(form.premier_message) }}
                    {{ form_widget(form.premier_message) }}

                    <small>{{ form_help(form.premier_message) }}</small>

                    <div class="form-error">
                        {{ form_errors(form.premier_message) }}
                    </div>
                </div>
                <div class="block_submit">
                    <div class="bloc_form btn-custom">
                        <span class="hover-effect">
                        {{ form_widget(form.submit, {attr : {class : ' '}}) }}
                        </span>
                    </div>
                </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}