src/Entity/Boutique.php
<?php

namespace App\Entity;

use App\Repository\BoutiqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BoutiqueRepository::class)]
class Boutique
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(
    min: 3,
    max: 255,
    minMessage: 'Votre titre doit faire au moins {{ limit }} caractères de long',
    maxMessage: 'Votre titre doit faire au maxmium {{ limit }} caractères de long',
    )]
    #[Assert\NotBlank(message: 'Veuillez renseigner ce champ')]
    private $title;

    #[ORM\Column(type: 'text', nullable: true)]
    #[Assert\Length(
    max: 1200,
    maxMessage: 'Votre description doit faire au maxmium {{ limit }} caractères de long',
    )]
    private $description;

    #[ORM\Column(type: 'string' , length: 255, nullable: true)]
    #[Assert\Length(
    min: 10,
    max: 10,
    minMessage: ' {{ limit }} chiffres minimum !',
    maxMessage: '{{ limit }} chiffres maximum ! ',
    )]
    #[Assert\Type(
    type: 'numeric',
    message: 'Mauvais format',
    )]
    private $telephone;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $adress;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;

    #[ORM\Column(type: 'integer')]
    private $postcode;

    #[ORM\Column(type: 'integer')]
    private $citycode;

    #[ORM\Column(type: 'float')]
    private $lat;

    #[ORM\Column(type: 'float')]
    private $lng;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Gedmo\Timestampable(on: 'create')]
    private $created_at;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $modified_at;

    #[ORM\Column(type: 'boolean')]
    private $actif;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'boutiques')]
    private $user;

    #[ORM\OneToMany(mappedBy: 'boutique', targetEntity: ImagesBoutique::class)]
    private $imagesBoutiques;

    #[ORM\OneToMany(mappedBy: 'boutique', targetEntity: Annonce::class)]
    private $annonces;

    #[ORM\OneToMany(mappedBy: 'boutique', targetEntity: Avis::class)]
    private $avis;

    #[ORM\OneToMany(mappedBy: 'boutique', targetEntity: Favory::class)]
    private $favories;

    #[ORM\Column(type: 'boolean')]
    private $card_active;


    public function __construct()
    {
        $this->imagesBoutiques = new ArrayCollection();
        $this->annonces = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->user = new ArrayCollection();
        $this->favories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTelephone()
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }


    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTimeImmutable $modified_at): self
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, ImagesBoutique>
     */
    public function getImagesBoutiques(): Collection
    {
        return $this->imagesBoutiques;
    }

    public function addImagesBoutique(ImagesBoutique $imagesBoutique): self
    {
        if (!$this->imagesBoutiques->contains($imagesBoutique)) {
            $this->imagesBoutiques[] = $imagesBoutique;
            $imagesBoutique->setBoutique($this);
        }

        return $this;
    }

    public function removeImagesBoutique(ImagesBoutique $imagesBoutique): self
    {
        if ($this->imagesBoutiques->removeElement($imagesBoutique)) {
            // set the owning side to null (unless already changed)
            if ($imagesBoutique->getBoutique() === $this) {
                $imagesBoutique->setBoutique(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Annonce>
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setBoutique($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getBoutique() === $this) {
                $annonce->setBoutique(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvis(Avis $avi): self
    {
        if (!$this->avis->contains($avi)) {
            $this->avis[] = $avi;
            $avi->setBoutique($this);
        }
        return $this;
    }

    public function removeAvis(Avis $avi): self
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getBoutique() === $this) {
                $avi->setBoutique(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, Favory>
     */
    public function getFavories(): Collection
    {
        return $this->favories;
    }

    public function addFavory(Favory $favory): self
    {
        if (!$this->favories->contains($favory)) {
            $this->favories[] = $favory;
            $favory->setBoutique($this);
        }

        return $this;
    }

    public function removeFavory(Favory $favory): self
    {
        if ($this->favories->removeElement($favory)) {
            // set the owning side to null (unless already changed)
            if ($favory->getBoutique() === $this) {
                $favory->setBoutique(null);
            }
        }

        return $this;
    }

    public function isCardActive(): ?bool
    {
        return $this->card_active;
    }

    public function setCardActive(bool $card_active): self
    {
        $this->card_active = $card_active;

        return $this;
    }

    public function getCitycode(): ?string
    {
        return $this->citycode;
    }

    public function setCitycode(?string $citycode): self
    {
        $this->citycode = $citycode;

        return $this;
    }

    public function getPostcode(): ?int
    {
        return $this->postcode;
    }

    public function setPostcode(int $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }
}

src/Entity/Subcategory.php
<?php

namespace App\Entity;

use App\Repository\SubcategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SubcategoryRepository::class)]
class Subcategory
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    
    #[Assert\NotBlank(message: 'Veuillez renseigner un titre')]
    #[Assert\Length(min: 3, minMessage: 'Votre titre est trop court')]
    private $title;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'subcategories')]
    #[ORM\JoinColumn(nullable: false)]
    private $parent_category;

    #[ORM\OneToMany(mappedBy: 'subcategory', targetEntity: Annonce::class)]
    private $annonces;

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getParentCategory(): ?Category
    {
        return $this->parent_category;
    }

    public function setParentCategory(?Category $parent_category): self
    {
        $this->parent_category = $parent_category;

        return $this;
    }

    /**
     * @return Collection<int, Annonce>
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setSubcategory($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getSubcategory() === $this) {
                $annonce->setSubcategory(null);
            }
        }

        return $this;
    }
}

src/Controller/Boutique/AnnonceController.php
<?php

namespace App\Controller\Boutique;

use App\Entity\Annonce;
use App\Entity\Boutique;
use App\Form\AnnonceType;
use App\Repository\FavoryRepository;
use App\Service\UploadImage;
use App\Entity\ImagesAnnonces;
use App\Controller\DefaultController;
use App\Repository\AnnonceRepository;
use App\Repository\ImagesAnnoncesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/boutique/annonce')]
class AnnonceController extends AbstractController
{
    #[Route('/', name: 'app_annonce_index', methods: ['GET'])]
    public function indexAnnonce(): Response
    {
        $user = $this->getUser();
        $boutiques = $user->getBoutiques();
        $boutique = $boutiques[0];
        $annonces = $boutique->getAnnonces();

        return $this->render('front/annonce/index_annonce.html.twig', [
            'annonces' => $annonces,
        ]);
    }

    #[Route('/new', name: 'app_annonce_new', methods: ['GET', 'POST'])]
    public function newAnnonce(Request $request, BoutiqueController $boutiqueController,AnnonceRepository $annonceRepository, UploadImage $uploadImage, ImagesAnnoncesRepository $imagesAnnoncesRepository): Response
    {
        $boutique = $boutiqueController->getUserBoutique();

        $annonce = new Annonce();
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annonce->setBoutique($boutique);
            $annonce->setActif(1);
            $annonce->setCreatedAt(new \DateTimeImmutable());
            $annonceRepository->add($annonce, true);
            $annonceImages = $form->get('upload')->getData();
            if (count($annonceImages) <= 4 || empty($annonceImages)) {
                if (empty($annonceImages)) {
                    $imageDefault = new ImagesAnnonces();
                    $imageDefault->setTitle('logo-sans-fond.png');
                    $imageDefault->setAnnonce($annonce);
                    $imagesAnnoncesRepository->add($imageDefault, true);
                } else {
                    $uploadImage->uploadAndResizeImage($annonceImages, $annonce);
                }
            } else {
                $this->addFlash('failure', '4 photos max !');
                return $this->redirectToRoute('app_annonce_new', [], Response::HTTP_SEE_OTHER);
            }
            return $this->redirectToRoute('app_annonce_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/annonce/new_annonce.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    #[Route('/edit/{id}', name: 'app_annonce_edit', methods: ['GET', 'POST'])]
    public function editAnnonce(Request $request, BoutiqueController $boutiqueController,Annonce $annonce, AnnonceRepository $annonceRepository, UploadImage $uploadImage): Response
    {
        $boutique = $boutiqueController->getUserBoutique();

        // L'annnonce est elle bien associée à la boutique?
        if ($annonce->getBoutique() !== $boutique) {
            return $this->redirectToRoute('403', [], Response::HTTP_SEE_OTHER);
        }

        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annonce->setModifiedAt(new \DateTimeImmutable());
            $annonceRepository->add($annonce, true);
            $annonceImages = $form->get('upload')->getData();
            if (count($annonceImages) <= 4 || empty($annonceImages)) {
                $uploadImage->uploadAndResizeImage($annonceImages, $annonce);
            } else {
                $this->addFlash('failure', '4 photos max !');
                return $this->redirectToRoute('app_annonce_new', [], Response::HTTP_SEE_OTHER);
            }
            return $this->redirectToRoute('app_annonce_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/annonce/edit_annonce.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_annonce_delete', methods: ['POST', 'GET'])]
    public function deleteAnnonce($id, Request $request, Annonce $annonce, AnnonceRepository $annonceRepository, ImagesAnnoncesRepository $imagesAnnoncesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $annonce->getId(), $request->request->get('_token'))) {
            $imagesAnnonce = $imagesAnnoncesRepository->findImagesbyAnnonceId($id);
            foreach ($imagesAnnonce as $image) {
                $imagesAnnoncesRepository->remove($image, true);
            }
            $annonceRepository->remove($annonce, true);
        }

        return $this->redirectToRoute('app_annonce_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/actif/{id}', name: 'app_annonce_actif', methods: ['POST', 'GET'])]
    public function toggleActif(Annonce $annonce, AnnonceRepository $annonceRepository): Response
    {
        if ($annonce->isActif()) {
            $annonce->setActif(false);
        } else {
            $annonce->setActif(true);
        }
        $annonceRepository->add($annonce, true);

        return $this->redirectToRoute('app_annonce_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Boutique/PreferencesController.php
<?php

namespace App\Controller\Boutique;

use App\Entity\Boutique;
use App\Repository\BoutiqueRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/boutique')]
class PreferencesController extends AbstractController
{
    #[Route('/mespreferences', name: 'app_boutique_preference')]
    public function indexPreference(){
        $user = $this->getUser();
        $boutiques = $user->getBoutiques();
        $boutique = $boutiques[0];
        return $this->render('front/boutique/preferences/mespreferences.html.twig', [
            'boutique' => $boutique
        ]);
    }

    #[Route('/mespreferences/card', name: 'app_toggle_cardActive')]
    public function toggleCardActive(BoutiqueRepository $boutiqueRepository): Response
    {
        $user = $this->getUser();
        $boutiques = $user->getBoutiques();
        $boutique = $boutiques[0];
        if ($boutique->isCardActive()) {
            $boutique->setCardActive(0);
        }else{
            $boutique->setCardActive(1);
        }
        $boutiqueRepository->add($boutique,true);

        return $this->redirectToRoute('app_boutique_preference', [], Response::HTTP_SEE_OTHER);
    }
}

templates/front/boutique/_delete_form.html.twig
<form class="inline-block" method="post" action="{{ path('app_boutique_delete', {'id': boutique.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer votre boutique ? Vous avez la possibilité de désactiver votre boutique afin de la rendre invisible aux autres utilisateurs.');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ boutique.id) }}">
    <button class="block_btn_delete">
        <div class="bloc_form btn-custom delete">
            <span class="hover-effect delete">
                <a title="Supprimer la boutique"><i class="fa-solid fa-trash"></i></a>
            </span>
        </div>
    </button>
</form>

templates/front/boutique/edit_boutique.html.twig
{% extends 'layout/boutique_base.html.twig' %}

{% block stylesheets %}
    {{ encore_entry_link_tags('Formulaires') }}
{% endblock %}

{% block title %}
    <title>Modifier ma Boutique</title>
{% endblock %}

{% block body %}
    <h1 class="title_top">Modifier ma boutique</h1>
    {{ include('front/boutique/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('Formulaires') }}
{% endblock %}

templates/front/boutique/index_boutique.html.twig
{% extends 'layout/boutique_base.html.twig' %}

{% block title %}
    <title>Espace boutique</title>
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('index_boutique') }}
{% endblock %}

{% block body %}
    <section class="boutique_accueil">
        <div class="wrap">
            <h1 class="title_top"> {{ boutique.title }} </h1>
            <div class="wrapper_text_boutique">
                <div class="txt_top_boutique">
                    <h3 class="welcome">Bienvenue sur votre espace boutique&nbsp;!</h3>
                    <div class="message_info">
                        <p>D'ici, vous pouvez :</p>
                        <ul>
                            <li>- voir et gérer vos boutiques favorites,</li>
                            <li>- accéder aux informations de votre boutique et les modifier (photo, description, coordonnées),</li>
                            <li>- ajouter vos annonces, les modifier, les supprimer ou les désactiver temporairement...,</li>
                            <li>- voir les avis que vous avez reçus, gérer ceux que vous avez émis (les modifier ou les supprimer), </li>
                            <li>- accéder à vos messages </li>
                        </ul>
                    </div>
                </div>
                <div class="txt_bottom_boutique">
                    <div class="bloc_form btn-custom btq">
                        <span class="hover-effect btq">
                            <a title="Voir ma boutique" href="{{ path('view_boutique', {'id' : boutique.id }) }}">Voir ma boutique</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}


{% block javascripts %}
    {{ encore_entry_script_tags('index_boutique') }}
{% endblock %}

templates/front/boutique/viewboutique.html.twig
{% extends 'layout/front_base.html.twig' %}

{% block title %}
    {% if annonce == null %}
        {{ boutique.title }}
    {% else %}
        {{ annonce.title }}
    {% endif %}
{% endblock %}

{% block stylesheets %}
    {% if annonce != null %}
        {{ encore_entry_link_tags('public_boutique') }}
        {{ encore_entry_link_tags('Formulaires') }}
    {% else %}
        {{ encore_entry_link_tags('focus_annonce') }}
    {% endif %}
    <link href="{{ asset('bootstrap/sb-admin-2.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
    <section id="slider-home_boutique">
        {% include '_partials/_images_boutique.html.twig' %}
        <a href="{{ path('view_boutique', {id: boutique.id}) }}" title="Cliquez pour voir la boutique en détail">
            <div class="photo_profile">
                {% if user.image|length != NULL %}
                    {% if boutique.user.id > 53 or boutique.user.id == 1 or boutique.user.id == 2 or boutique.user.id == 3  %}
                        <img src="{{ asset('uploads/profile/' ~ user.image) }}" alt="Photo de profil" />
                    {% else %}
                        <img src="{{ user.image }}" alt="Photo de profil"  />
                    {% endif %}
                {% else %}
                    <img src="{{ asset('uploads/profile/incognito-62f7bceeb2bee.png') }}" alt="Photo de profil"  />
                {% endif %}
            </div>
        </a>
    </section>
    <section id="profile" class="wrap">
        <div class="infos_vendeur">
            <p>{{ boutique.user.name|capitalize }}&nbsp;|</p>
            <p>Boutique en ligne depuis le {{ boutique.createdAt|date('d/m/Y') }}</p>
        </div>
    </section>
    <section id="boutique" class="wrap padding-10">
        <div class="head_boutique">
            <div class="head_btq_line">
                <div>
                    <h1 class="title_boutique">
                        <a title="Cliquez pour voir la boutique en détail" href="{{ path('view_boutique', {id: boutique.id}) }}">
                            {{ boutique.title }}
                        </a>
                    </h1>
                </div>
                {% if app.user and notMyboutique %}
                    <div class="favory_boutique">
                        <a title="Ajouter aux favoris" class="favory_button {{ favory }}" href="{{ path('app_toggle_favory', {'id' : boutique.id}) }}"><i class="favory_icon fa-solid fa-heart"></i></a>
                    </div>
                {% endif %}
            </div>
            {% if annonce == null %}
                <div class="rating_boutique">
                    <a href="#avis_listing" title="Les avis">
                        <span class="rating" data-rating="{{ globalRating }}">
                            {% for i in 1..5 %}
                                {% if i <= globalRating|round %}
                                    {% if (i - globalRating) > 0  %}
                                        <i class="fa-solid fa-star-half-stroke favory" data-checked="false" data-note="{{ i }}"></i>
                                    {% else %}
                                        <i class="fa-solid fa-star favory" data-checked="false" data-note="{{ i }}"></i>
                                    {% endif %}
                                {% else %}
                                    <i class="fa-regular fa-star favory" data-checked="false" data-note="{{ i }}"></i>
                                {% endif %}
                            {% endfor %}
                        </span>
                    </a>
                    <span>({{ avis|length }} avis)</span>
                </div>
                <p class="description_boutique">{{ boutique.description }}</p>
            {% endif %}
        </div>
    </section>
    {% if annonce == null and boutique.cardActive %}
        {% if boutique.adress == '' %}
            {% set fullAdress = 'false' %}
        {% else %}
            {% set fullAdress = 'true' %}
        {% endif %}
        <section class="wrap">
            <h1 class="title_boutique">Où me trouver ?</h1>
            <div id="boutique_coordinates" style="" data-full="{{ fullAdress }}" data-boutique_title="{{ boutique.title }}" data-lng="{{boutique.lng}}" data-lat="{{boutique.lat}}"></div>
        </section>
    {% endif %}
    {% if annonce != null %}
        <section id="focus_annonce" class="wrap">
            <div class="annonce_box">
{#                {% include '_partials/_images_annonce.html.twig' %}#}
                <div class="annonce_img image-card flexslider slider-annonce ">
                    <ul class="slides">
                        {% for image in annonce.imagesAnnonces %}
                            <li class="li_annonce_img">
                                <img src="{{ asset('uploads/annonce/'~ image.title) }}" alt="image annonce">
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="annonce_text">
                    <h5 class="annonce_title">{{ annonce.title }}&nbsp;&nbsp;<span class="span_created">Mis en ligne le {{ annonce.createdAt|date('d/m/Y') }}</span></h5>
                    <p class="annonce_type"><strong>Catégorie : </strong>{{ annonce.subcategory.parentCategory.title }}</p>
                    <p class="annonce_type"><span>Type de produit : </span>{{ annonce.subcategory.title }}</p>
                    <span>Description : </span>
                    <p class="annonce_description scroller">{{ annonce.description }}</p>
                    <p class="annonce_price">{{ annonce.price }}€/{{ annonce.mesure.title }}</p>
                </div>
            </div>
            {% if notMyboutique %}
                <div class="contact_vendeur">
                    {% if app.user %}
                        <div>
                            <p class="contact">Contacter le vendeur</p>
                        </div>
                        <div class="resp_contact">
                            {% if boutique.telephone %}
                                <p class="telephone">{{ boutique.telephone }}</p>
                            {% endif %}
                            {% if is_granted('ROLE_VENDEUR') %}
                                <a title="Envoyer un message au vendeur" href="{{ path('boutique_messagerie_new_conversation', {id: annonce.boutique.user.id}) }}" class="message_link">Message</a>
                            {% else %}
                                <a title="Envoyer un message au vendeur" href="{{ path('new_conversation_user', {id: annonce.boutique.user.id}) }}" class="message_link">Message</a>
                            {% endif %}
                        </div>
                    {% else %}
                        <div>
                            <p class="contact">Contacter le vendeur</p>
                        </div>
                        <div class="resp_contact">
                            <a class="message_visiteur" href="{{ path('app_login') }}">Connectez vous</a>
                            <p class="text-center">ou</p>
                            <a class="message_visiteur" href="{{ path('app_register') }}">Inscrivez-vous</a>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        </section>
    {% endif %}

    {% if annonce == null %}
        {% if boutique.annonces|length > 0 %}
        <section id="listing_annonces_public" class="wrap">
            <h1 class="title_boutique">Les annonces de {{  boutique.user.name|capitalize }}</h1>
            {% include 'front/annonce/_annonces.html.twig' %}
        </section>
         {% else %}
            <div class="m-5"></div>
        {% endif %}
    {% else %}
        {% if boutique.annonces|length > 1 %}
        <section id="listing_annonces_public" class="wrap">
            <h1 class="title_boutique">Les autres annonces de {{  boutique.user.name|capitalize }}</h1>
            {% include 'front/annonce/_annonces.html.twig' %}
        </section>
        {% else %}
            <div class="m-5"></div>
        {% endif %}
    {% endif %}

    {% if annonce == null %}
        {% include 'front/boutique/avis/_avis_boutique.html.twig' %}
    {% endif %}
{% endblock %}

{% block javascripts %}
    {% if annonce == null %}
        {{ encore_entry_script_tags('public_boutique') }}
        {{ encore_entry_script_tags('Formulaires') }}
    {% else %}
        {{ encore_entry_script_tags('focus_annonce') }}
    {% endif %}
    <script>
        $(document).ready(function () {
            const boutton_favory =    $('.favory_button')
            boutton_favory.click( function (e) {
                e.preventDefault();
                let path = '{{ path('app_toggle_favory', {id:boutique.id}) }}';
                $.ajax({
                    type: "POST",
                    url: path,
                    dataType : 'html',
                    data: {{ boutique.id }},
                    success: function(res){
                        if (boutton_favory.hasClass('favory_active')){
                            boutton_favory.removeClass('favory_active')
                        }else{
                            boutton_favory.addClass('favory_active')
                        }
                    }
                });
            })
        })
    </script>
{% endblock %}